### ISSUE TITLE
API Endpoints Backlog Tracker

### ISSUE THREAD

**Issue by aero31aero** [zulip/zulip-js#63]
Over the past 2 months, we've had some endpoints added to the python api bindings that haven't been added here yet. This issue is to track such endpoints.

- [ ] DELETE /messages/<message_id>.
- [ ] DELETE /messages/<message_id>/reactions.
- [ ] DELETE /realm/filters/<filter_id>.
- [ ] DELETE /user_groups/<user_group_id>.
- [ ] DELETE /users/me/alert_words.
- [ ] GET /messages.
- [ ] GET /messages/<message_id>.
- [ ] GET /messages/<message_id>/history.
- [ ] GET /realm/emoji.
- [ ] GET /realm/filters.
- [ ] GET /server_settings.
- [ ] GET /users/me/alert_words.
- [ ] PATCH /settings/notifications.
- [ ] PATCH /streams/<stream_id>.
- [ ] PATCH /user_groups/<user_group_id>.
- [ ] PATCH /users/me/subscriptions/muted_topics.
- [ ] POST /mark_all_as_read.
- [ ] POST /mark_stream_as_read.
- [ ] POST /mark_topic_as_read.
- [ ] POST /messages/flags.
- [ ] POST /messages/<message_id>/reactions.
- [ ] POST /realm/filters.
- [ ] POST /typing.
- [ ] POST /user_groups/create.
- [ ] POST /user_groups/<user_group_id>/members.
- [ ] POST /users/me/alert_words.
- [ ] POST /users/me/presence.
- [ ] POST /users/me/subscriptions/properties.

**Comment by Milind712000** [comment]
The following api have been added 
- GET /realm/filters (in #68 )
- GET /server_settings (in #66 )

Please update the tracker

**Comment by aero31aero** [comment]
Thanks, updated the list.

**Comment by Ctrl-apk** [comment]
Hi, I’d like to work on this issue. @zulipbot claim
